[platformio]
default_envs = esp32

[common]
framework = arduino, espidf
pioarduino_platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.32/platform-espressif32.zip
lib_deps =
    https://github.com/me-no-dev/ESPAsyncWebServer.git
    https://github.com/me-no-dev/AsyncTCP.git
build_flags =
    -I include
    -DESP_IDF_LWIP_HOOK_FILENAME=\"lwip_hooks.h\"
monitor_speed = 115200
board_build.partitions = min_spiffs.csv
extra_scripts = pre:tools/platformio_progname.py

[env:esp32]
platform = ${common.pioarduino_platform}
board = esp32dev
framework = ${common.framework}
lib_deps = ${common.lib_deps}
build_flags =
    ${common.build_flags}
    -DTWAI_TX_PIN=5
    -DTWAI_RX_PIN=4
    -DPIN_LED=2
    -DOTA_RELEASE_ASSET_NAME=\"fsd-controller-esp32-ota.bin\"
monitor_speed = ${common.monitor_speed}
board_build.partitions = ${common.board_build.partitions}
board_build.sdkconfig_defaults =
    sdkconfig.defaults
    sdkconfig.esp32.defaults
extra_scripts = ${common.extra_scripts}
custom_progname = fsd-controller-esp32

[env:esp32c3]
platform = ${common.pioarduino_platform}
board = esp32-c3-devkitm-1
framework = ${common.framework}
lib_deps = ${common.lib_deps}
build_flags =
    ${common.build_flags}
    -DTWAI_TX_PIN=5
    -DTWAI_RX_PIN=4
    -DPIN_LED=8
    -DOTA_RELEASE_ASSET_NAME=\"fsd-controller-esp32c3-ota.bin\"
monitor_speed = ${common.monitor_speed}
board_build.flash_size = 4MB
board_upload.flash_size = 4MB
board_build.partitions = ${common.board_build.partitions}
board_build.sdkconfig_defaults =
    sdkconfig.defaults
    sdkconfig.esp32c3.defaults
extra_scripts = ${common.extra_scripts}
custom_progname = fsd-controller-esp32c3

[env:esp32c5]
platform = ${common.pioarduino_platform}
board = esp32-c5-wifi6-kit-n16r4
framework = ${common.framework}
lib_deps = ${common.lib_deps}
build_flags =
    ${common.build_flags}
    -DTWAI_TX_PIN=5
    -DTWAI_RX_PIN=4
    -DPIN_LED=27
    -DOTA_RELEASE_ASSET_NAME=\"fsd-controller-esp32c5-ota.bin\"
monitor_speed = ${common.monitor_speed}
board_build.flash_size = 16MB
board_upload.flash_size = 16MB
board_build.partitions = ${common.board_build.partitions}
board_build.sdkconfig_defaults =
    sdkconfig.defaults
    sdkconfig.esp32c5.defaults
extra_scripts = ${common.extra_scripts}
custom_progname = fsd-controller-esp32c5

[env:esp32c6]
platform = ${common.pioarduino_platform}
board = esp32-c6-devkitc-1
framework = ${common.framework}
lib_deps = ${common.lib_deps}
build_flags =
    ${common.build_flags}
    -DTWAI_TX_PIN=5
    -DTWAI_RX_PIN=4
    -DPIN_LED=8
    -DOTA_RELEASE_ASSET_NAME=\"fsd-controller-esp32c6-ota.bin\"
monitor_speed = ${common.monitor_speed}
board_build.flash_size = 8MB
board_upload.flash_size = 8MB
board_build.partitions = ${common.board_build.partitions}
board_build.sdkconfig_defaults =
    sdkconfig.defaults
    sdkconfig.esp32c6.defaults
extra_scripts = ${common.extra_scripts}
custom_progname = fsd-controller-esp32c6

[env:esp32s3]
platform = ${common.pioarduino_platform}
board = esp32-s3-devkitc-1
framework = ${common.framework}
lib_deps = ${common.lib_deps}
build_flags =
    ${common.build_flags}
    -DTWAI_TX_PIN=15
    -DTWAI_RX_PIN=16
    -DPIN_LED=48
    -DOTA_RELEASE_ASSET_NAME=\"fsd-controller-esp32s3-ota.bin\"
monitor_speed = ${common.monitor_speed}
board_build.flash_size = 8MB
board_upload.flash_size = 8MB
board_build.partitions = ${common.board_build.partitions}
board_build.sdkconfig_defaults =
    sdkconfig.defaults
    sdkconfig.esp32s3.defaults
extra_scripts = ${common.extra_scripts}
custom_progname = fsd-controller-esp32s3
